config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    member do
      patch :complete
    end
  end

  root 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  enum status: { pending: 0, complete: 1 }
  
  validates :title, :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update, :destroy, :complete]

  def index
    @filter = params[:filter] || 'all'
    @tasks = case @filter
             when 'pending'
               Task.pending
             when 'complete'
               Task.complete
             else
               Task.all.order(created_at: :desc)
             end
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task.update(task_params)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: 'Task was successfully deleted.'
  end

  def complete
    @task.complete!
    redirect_to tasks_path, notice: 'Task marked as complete.'
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KadinceTodo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<% view_variables = task.persisted? ? { path: task_path(task), method: :patch, modal_title: 'Update Task' } : { path: tasks_path, method: :post, modal_title: 'Create Task' } %>
<%= form_with(model: task, url: view_variables[:url], method: view_variables[:method], remote: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="modal-header">
    <h5 class="modal-title" id="newTaskModalLabel"><%= view_variables[:modal_title] %></h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    <div class="mb-3">
      <%= form.label :title, class: "form-label" %>
      <%= form.text_field :title, class: "form-control", required: true %>
    </div>
    <div class="mb-3">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_area :description, class: "form-control" %>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <%= form.submit view_variables[:modal_title], class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/_refresh_form.js.erb
<% if task.errors.present? %>
  $("#modal-form-body").html("<%= j render partial: 'form', locals: { task: task } %>")
<% else %>
  $("#task-modal").modal('hide')
  window.location.href = '/tasks'
<% end %>

app/views/tasks/_task.html.erb
<li class="list-group-item d-flex justify-content-between align-items-center">
  <div>
    <% if task.complete? %>
      <del><%= task.title %></del>
    <% else %>
      <%= task.title %>
    <% end %>
    <br>
    <small class="text-muted"><%= truncate(task.description, length: 50) %></small>
  </div>
  <div>
    <% unless task.complete? %>
      <%= link_to complete_task_path(task), method: :patch, class: "btn btn-sm btn-success me-2" do %>
        <i class="bi bi-check-circle"></i> Complete
      <% end %>
      <%= link_to edit_task_path(task), class: "btn btn-sm btn-primary me-2", remote: true do %>
        <i class="bi bi-pencil-square"></i> Edit
      <% end %>
    <% end %>
    <%= link_to task_path(task), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" do %>
      <i class="bi bi-trash"></i> Delete
    <% end %>
  </div>
</li>

app/views/tasks/create.js.erb
<%= render partial: "refresh_form", locals: { task: @task } %>

app/views/tasks/edit.js.erb
$("#task-modal").modal('show')
$("#modal-form-body").html("<%= j render partial: 'form', locals: { task: @task } %>")

app/views/tasks/index.html.erb
<div class="container mt-5">
  <h1>My Todo List</h1>

  <div class="mb-3">
    <%= link_to "All", tasks_path(filter: 'all'), class: "btn btn-outline-primary #{'active' if @filter == 'all'}" %>
    <%= link_to "Pending", tasks_path(filter: 'pending'), class: "btn btn-outline-primary #{'active' if @filter == 'pending'}" %>
    <%= link_to "Complete", tasks_path(filter: 'complete'), class: "btn btn-outline-primary #{'active' if @filter == 'complete'}" %>
    <%= link_to 'Add New Task', new_task_path, class: 'btn btn-success float-end', remote: true %>
  </div>

  <ul class="list-group">
    <% @tasks.each do |task| %>
      <%= render task %>
    <% end %>
  </ul>
</div>

<div class="modal fade" id="task-modal" tabindex="-1" aria-labelledby="taskModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" id="modal-form-body">
      <%= render partial: 'form', locals: { task: Task.new }%>
    </div>
  </div>
</div>

app/views/tasks/new.js.erb
$("#task-modal").modal('show')
$("#modal-form-body").html("<%= j render partial: 'form', locals: { task: Task.new } %>")

app/views/tasks/update.js.erb
<%= render partial: "refresh_form", locals: { task: @task } %>